# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='pstar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pstar_author', to='main.Pstar'),
        ),
    ]
