# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 04:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tweet_pstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pstar',
            name='profile_image',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'images': {}}),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='pstar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='main.Pstar'),
        ),
    ]
